# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vcz/projects/cpp/SoulBoundcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vcz/projects/cpp/SoulBoundcpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vcz/projects/cpp/SoulBoundcpp/CMakeFiles /home/vcz/projects/cpp/SoulBoundcpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vcz/projects/cpp/SoulBoundcpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SoulBound

# Build rule for target.
SoulBound: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SoulBound
.PHONY : SoulBound

# fast build rule for target.
SoulBound/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/build
.PHONY : SoulBound/fast

src/assetHandling/Font.o: src/assetHandling/Font.cc.o
.PHONY : src/assetHandling/Font.o

# target to build an object file
src/assetHandling/Font.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/assetHandling/Font.cc.o
.PHONY : src/assetHandling/Font.cc.o

src/assetHandling/Font.i: src/assetHandling/Font.cc.i
.PHONY : src/assetHandling/Font.i

# target to preprocess a source file
src/assetHandling/Font.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/assetHandling/Font.cc.i
.PHONY : src/assetHandling/Font.cc.i

src/assetHandling/Font.s: src/assetHandling/Font.cc.s
.PHONY : src/assetHandling/Font.s

# target to generate assembly for a file
src/assetHandling/Font.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/assetHandling/Font.cc.s
.PHONY : src/assetHandling/Font.cc.s

src/assetHandling/UI/UI_Button.o: src/assetHandling/UI/UI_Button.cc.o
.PHONY : src/assetHandling/UI/UI_Button.o

# target to build an object file
src/assetHandling/UI/UI_Button.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/assetHandling/UI/UI_Button.cc.o
.PHONY : src/assetHandling/UI/UI_Button.cc.o

src/assetHandling/UI/UI_Button.i: src/assetHandling/UI/UI_Button.cc.i
.PHONY : src/assetHandling/UI/UI_Button.i

# target to preprocess a source file
src/assetHandling/UI/UI_Button.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/assetHandling/UI/UI_Button.cc.i
.PHONY : src/assetHandling/UI/UI_Button.cc.i

src/assetHandling/UI/UI_Button.s: src/assetHandling/UI/UI_Button.cc.s
.PHONY : src/assetHandling/UI/UI_Button.s

# target to generate assembly for a file
src/assetHandling/UI/UI_Button.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/assetHandling/UI/UI_Button.cc.s
.PHONY : src/assetHandling/UI/UI_Button.cc.s

src/entities/Camera.o: src/entities/Camera.cc.o
.PHONY : src/entities/Camera.o

# target to build an object file
src/entities/Camera.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/entities/Camera.cc.o
.PHONY : src/entities/Camera.cc.o

src/entities/Camera.i: src/entities/Camera.cc.i
.PHONY : src/entities/Camera.i

# target to preprocess a source file
src/entities/Camera.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/entities/Camera.cc.i
.PHONY : src/entities/Camera.cc.i

src/entities/Camera.s: src/entities/Camera.cc.s
.PHONY : src/entities/Camera.s

# target to generate assembly for a file
src/entities/Camera.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/entities/Camera.cc.s
.PHONY : src/entities/Camera.cc.s

src/entities/Player.o: src/entities/Player.cc.o
.PHONY : src/entities/Player.o

# target to build an object file
src/entities/Player.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/entities/Player.cc.o
.PHONY : src/entities/Player.cc.o

src/entities/Player.i: src/entities/Player.cc.i
.PHONY : src/entities/Player.i

# target to preprocess a source file
src/entities/Player.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/entities/Player.cc.i
.PHONY : src/entities/Player.cc.i

src/entities/Player.s: src/entities/Player.cc.s
.PHONY : src/entities/Player.s

# target to generate assembly for a file
src/entities/Player.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/entities/Player.cc.s
.PHONY : src/entities/Player.cc.s

src/main/Config.o: src/main/Config.cc.o
.PHONY : src/main/Config.o

# target to build an object file
src/main/Config.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/main/Config.cc.o
.PHONY : src/main/Config.cc.o

src/main/Config.i: src/main/Config.cc.i
.PHONY : src/main/Config.i

# target to preprocess a source file
src/main/Config.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/main/Config.cc.i
.PHONY : src/main/Config.cc.i

src/main/Config.s: src/main/Config.cc.s
.PHONY : src/main/Config.s

# target to generate assembly for a file
src/main/Config.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/main/Config.cc.s
.PHONY : src/main/Config.cc.s

src/main/Engine.o: src/main/Engine.cc.o
.PHONY : src/main/Engine.o

# target to build an object file
src/main/Engine.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/main/Engine.cc.o
.PHONY : src/main/Engine.cc.o

src/main/Engine.i: src/main/Engine.cc.i
.PHONY : src/main/Engine.i

# target to preprocess a source file
src/main/Engine.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/main/Engine.cc.i
.PHONY : src/main/Engine.cc.i

src/main/Engine.s: src/main/Engine.cc.s
.PHONY : src/main/Engine.s

# target to generate assembly for a file
src/main/Engine.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/main/Engine.cc.s
.PHONY : src/main/Engine.cc.s

src/main/Level.o: src/main/Level.cc.o
.PHONY : src/main/Level.o

# target to build an object file
src/main/Level.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/main/Level.cc.o
.PHONY : src/main/Level.cc.o

src/main/Level.i: src/main/Level.cc.i
.PHONY : src/main/Level.i

# target to preprocess a source file
src/main/Level.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/main/Level.cc.i
.PHONY : src/main/Level.cc.i

src/main/Level.s: src/main/Level.cc.s
.PHONY : src/main/Level.s

# target to generate assembly for a file
src/main/Level.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/main/Level.cc.s
.PHONY : src/main/Level.cc.s

src/main/main.o: src/main/main.cc.o
.PHONY : src/main/main.o

# target to build an object file
src/main/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/main/main.cc.o
.PHONY : src/main/main.cc.o

src/main/main.i: src/main/main.cc.i
.PHONY : src/main/main.i

# target to preprocess a source file
src/main/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/main/main.cc.i
.PHONY : src/main/main.cc.i

src/main/main.s: src/main/main.cc.s
.PHONY : src/main/main.s

# target to generate assembly for a file
src/main/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SoulBound.dir/build.make CMakeFiles/SoulBound.dir/src/main/main.cc.s
.PHONY : src/main/main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SoulBound"
	@echo "... src/assetHandling/Font.o"
	@echo "... src/assetHandling/Font.i"
	@echo "... src/assetHandling/Font.s"
	@echo "... src/assetHandling/UI/UI_Button.o"
	@echo "... src/assetHandling/UI/UI_Button.i"
	@echo "... src/assetHandling/UI/UI_Button.s"
	@echo "... src/entities/Camera.o"
	@echo "... src/entities/Camera.i"
	@echo "... src/entities/Camera.s"
	@echo "... src/entities/Player.o"
	@echo "... src/entities/Player.i"
	@echo "... src/entities/Player.s"
	@echo "... src/main/Config.o"
	@echo "... src/main/Config.i"
	@echo "... src/main/Config.s"
	@echo "... src/main/Engine.o"
	@echo "... src/main/Engine.i"
	@echo "... src/main/Engine.s"
	@echo "... src/main/Level.o"
	@echo "... src/main/Level.i"
	@echo "... src/main/Level.s"
	@echo "... src/main/main.o"
	@echo "... src/main/main.i"
	@echo "... src/main/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

